### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './val/ILSVRC2012_validation_ground_truth.txt'

### ISSUE THREAD

**Issue by 1193700079** [Separius/SimCLRv2-Pytorch#3]
(pytorch) yrq@ssk-Linux:~/myproject/SimCLRv2-Pytorch$  python verify.py r50_1x_sk0.pth 

Traceback (most recent call last):
  File "/home/yrq/myproject/SimCLRv2-Pytorch/verify.py", line 71, in <module>
    run(args.pth_path)
  File "/home/yrq/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/yrq/myproject/SimCLRv2-Pytorch/verify.py", line 45, in run
    dataset = ImagenetValidationDataset('./val/')
  File "/home/yrq/myproject/SimCLRv2-Pytorch/verify.py", line 19, in __init__
    with open(os.path.join(val_path, 'ILSVRC2012_validation_ground_truth.txt')) as f:
FileNotFoundError: [Errno 2] No such file or directory: './val/ILSVRC2012_validation_ground_truth.txt'

**Comment by Separius** [comment]
you need to download the validation set of imagenet, if you did, check the ImagenetValidationDataset class and you will realize how to organize the files.
